# Generated by Django 2.1.3 on 2019-10-20 06:38

from django.db import migrations, models
import django.utils.timezone
import mysite.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, verbose_name='username')),
                ('password', models.CharField(max_length=150, verbose_name='パスワード')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('is_superuser', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date joined')),
            ],
            options={
                'verbose_name_plural': 'users',
                'db_table': 'user',
                'verbose_name': 'user',
            },
            managers=[
                ('objects', mysite.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='title')),
                ('tags', models.IntegerField(blank=True, null=True, verbose_name='tags')),
                ('category', models.IntegerField(blank=True, null=True, verbose_name='category')),
                ('image', models.CharField(blank=True, max_length=150, null=True, verbose_name='image')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='created at')),
            ],
            options={
                'verbose_name_plural': 'article',
                'db_table': 'article',
                'verbose_name': 'article',
            },
        ),
        migrations.CreateModel(
            name='CategoryInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='name')),
            ],
            options={
                'verbose_name_plural': 'category',
                'db_table': 'category',
                'verbose_name': 'category',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('article_id', models.IntegerField(blank=True, null=True, verbose_name='article id')),
                ('block', models.IntegerField(blank=True, null=True, verbose_name='block')),
                ('sub_title', models.CharField(blank=True, max_length=45, null=True, verbose_name='sub_title')),
                ('content', models.TextField(blank=True, max_length=1000, null=True, verbose_name='article')),
                ('image', models.CharField(blank=True, max_length=150, null=True, verbose_name='image')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='created at')),
            ],
            options={
                'verbose_name_plural': 'content',
                'db_table': 'contents',
                'verbose_name': 'content',
            },
        ),
        migrations.CreateModel(
            name='References',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('article_id', models.IntegerField(blank=True, null=True, verbose_name='article id')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('link', models.TextField(blank=True, null=True, verbose_name='link')),
                ('tmpfile', models.CharField(blank=True, max_length=255, null=True, verbose_name='tmpfile')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='created at')),
            ],
            options={
                'verbose_name_plural': 'link',
                'db_table': 'references',
                'verbose_name': 'link',
            },
        ),
        migrations.CreateModel(
            name='TagsInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='name')),
            ],
            options={
                'verbose_name_plural': 'tag',
                'db_table': 'tags',
                'verbose_name': 'tag',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'id',
                'db_table': 'test',
                'verbose_name': 'id',
            },
        ),
    ]
